
version: '3.0'

services:
  e2e-tests:
    build: .
    image: digitalmarketplace/e2e-tests
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /dev/shm:/dev/shm
      - .:/app
      - /app/node_modules
